export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const GET_ALL_PIZZA_LOADED = 'GET/PIZZA/ALL_LOADED'
export const ADD_TO_CART = 'ADD/TO_CART'
export const REMOVE_FROM_CART = 'REMOVE/FROM_CART'
